### PR TITLE
Adding an initial MLOps template

### PR DESCRIPTION
**Pull request by aslotte**
This PR includes the initial scaffolding of the project needed for model and validation test. I'll add the instructions and workflow file in the next PR's.

### CODE REVIEW

**Comment by aslotte** [comment]
@luisquintanilla this is ready for your review

**Comment by aslotte** [comment]
Yep, and it is just easier to understand the workflow file later as we'll run tests in a specific project. We could of course accomplish the same thing with `TestCategory` filters

**Comment by luisquintanilla** [comment]
I like it the way it is. Maybe a bit more to think about since now users are working with two test projects, but it's good practice. The only comment I'd make is, can we instead create a *test* directory in the root directory and put the tests in there instead of inside the *src* directory?

**Comment by aslotte** [comment]
Absolutely, I can look at that later today.

**Comment by aslotte** [comment]
@luisquintanilla  moved this to a test folder

**Pull request merged**
